<?php

namespace OC\PlatformBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;
/**
 * AdvertRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdvertRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAdverts()

    {
        $query = $this->createQueryBuilder('a')

            // Jointure sur l'attribut image
            ->leftJoin('a.image', 'i')
            ->addSelect('i')

            // Jointure sur l'attribut categories
            ->leftJoin('a.categories', 'c')
            ->addSelect('c')
            ->orderBy('a.date', 'DESC')

            ->getQuery()
        ;

        return $query->getResult();
    }
  }
  

